name: DeploymentTriggerTest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check PHP Version
        run: php -v

      - name: Check Composer Version
        run: composer -V

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run trigger
        run: php ./githubEventTrigger deployment --auth_http_token=${{ secrets.GITHUB_DEPLOYMENT_OAUTH_TOKEN }} --repository=${{ github.repository }}
